# Generated by Django 4.1.6 on 2023-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_paid",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
